### ISSUE TITLE
With fish/zsh shell, default binding of the up key to trigger Atuin may be problematic.

### ISSUE THREAD

**Issue by UbiquitousPhoton** [ellie/atuin#419]
When using the fish shell, the up key is used for a more than just to quickly access history, it is (for example) used to navigate through the pager of auto-suggestions/auto-completions. I thus found myself often triggering Atuin unintentionally whilst attempting to do so, which lead me to come here.

Whilst I am thinking of this, the same could potentially be said of zsh, with something like oh-my-zsh and completions enabled (just tested this, and this is indeed the case)

I'm not sure whether this issue exists in bash, I haven't used bash interactively in some time.

This is relatively low priority, as for now the workaround of defining ATUIN_NOBIND works, at least, but it might potentially mar the out of box experience. 

Unless the two different uses can be differentiated against (I'm not entirely sure they can be, reading the fish docs), then its possible that binding the up key by default may not be a good thing(tm).

**Comment by panekj** [comment]
I've said that before https://github.com/ellie/atuin/pull/234#issuecomment-991357343

**Comment by ellie** [comment]
@panekj what you've said, is a matter of personal preference.

What I'd like to establish here is if Atuin conflicts with the _default_ behaviour of the shell, as that is the only thing we can plan for.

**Comment by panekj** [comment]
> @panekj what you've said, is a matter of personal preference.

The matter of personal preference is stemmed from default shell preference and vice versa.
As other maintainer said (paraphrased), "It's annoying in the beginning, but you can get used to it"

It's okay to have different behaviour for different shells, I doubt that there is more than 5 people using differnt shells at the same time (not counting bash/sh since those tend to be default)
So as long as it's documented it will be fine.

I've tested it right now and it the binds are intrusive in places where they shouldn't be, so it does conflicts with fish

**Comment by ellie** [comment]
Your paraphrasing has changed the meaning there 😅

What was [actually said](https://github.com/ellie/atuin/issues/358#issuecomment-1129650505):

>  I found it intrusive in the beginning but now I struggle to use a terminal without it. 

Anyway.

----

I'm very hesitant to remove the up-arrow behaviour from defaults. I'm willing to do so if it really interferes with default shell behaviours, but less so if it's just an edge case. Afterall, disabling our default keybindings is not at all difficult. There will _always_ be people that like the defaults, and people that do not.

Because of features like sync, you will have an entirely different set of history while scrolling with the arrows than you will when pressing ctrl-R, which can cause even more confusion. 

> It's okay to have different behaviour for different shells

This is also something I want to avoid as much as possible. I do not want our documentation to state different things for different shells. Wherever possible, and unless there's a very strong reason to the contrary, features + default config should be unified and clear. 

>  binds are intrusive in places where they shouldn't be

The reason I asked @UbiquitousPhoton to open this issue is so that we can document these places + figure out a path forwards. If we can avoid bringing  opinions into this and state facts wherever possible, that would be fantastic :) If you could elaborate on the places you found conflicts that would be fantastic! Perhaps we could adjust our shell config to rebind them properly so it works.

**Comment by s0** [comment]
I'm a long-time user of fish, and have been using atuin for around 4/5 months now, and IMO the default "up" binding to trigger the tui makes sense, and should be kept as-is, for a number of reasons I'll elaborate on below.

It did take me some time to get used to it of course, like others, but that's always going to be the case when you're switching to using new tools that offer new / different features. It's unavoidable. If everything worked exactly the same as it did before, then you'd just habitually keep doing what you did, and then never actually use the new tools. They need to inject themselves somehow into your existing workflow for you to start using them and, eventually, be more productive.

So fish does of course by default have much better history navigating and suggestions that most shells... And we can all come to rely on that functionality, so I can also understand the jarring feeling when paging through your history suddenly changes and displays the tui instead. I had this too at the beginning, but this is the whole point of using atuin, it changes how you store & navigate your shell history. I wouldn't say that this binding interferes with fish's behaviour, I would say it replaces a feature (paging suggestions) with its own enhanced feature (searching through a tui of all your shell history across machines). Not to mention that it already pre-fills the tui with the command you'd already started writing... So in effect it's already filtered to display the commands that fish was going to page through anyway.

Beyond this, a few other thoughts are:

* consistency across shells is important (like @ellie said, having to provide different docs for different shells will confuse users, and will doubtlessly result in the opening of issues like "why doesn't up open atuin")
* It replaces & enhances, not interferes with (IMO) paging through suggestions
  * It pre-fills the tui with what you've already written, so there really isn't any lost functionality
* If people don't like this behaviour, either disable default keybindings (which is well documented), or just don't use atuin. (The whole point of using atuin is to enhance your history... So why should it not be the main way of navigating your history by default?)
* Not only do you get used to this behaviour, you end up relying on it and using it all the time
  * Switching from `up -> enter` to `up -> enter -> enter` to run the last command becomes a habit very quickly
  * Typing half a command, and then either `tab -> enter` or `up -> up -> enter` likewise becomes second nature.

I think that's all that occurs to me for now, just my 2c...

**Comment by panekj** [comment]
> It pre-fills the tui with what you've already written, so there really isn't any lost functionality

You seem to missed the point that it's not interfering when using shell history but when using file completion

**Comment by s0** [comment]
And almost immediately after posting my comment I realised that you are probably referring to a different feature than the one I was thinking of... :sweat_smile: 

I was interpreting that as "writing a command and then using arrows to navigate theough recent history suggestions" not "navigating through the grid of tab-completion suggestions"... and I imagine you mean the latter.

In that case what I will say in that regard is that most of what I said still holds true... and I _still_ think that binding to "up" by default is what atuin should do for now. And in the meantime, users can use `tab` and `shift+tab` to navigate tab-completion suggestions (instead of `up` and `down`, which tbh i never really use anyway).

**Comment by panekj** [comment]
> users can use `tab` and `shift+tab` to navigate tab-completion suggestions (instead of `up` and `down`, which tbh i never really use anyway).

Nope, because `tab` / `shift+tab` isn't always the same behaviour, in certain cases `shift+tab` will advance in suggestions instead of going back

**Comment by s0** [comment]
Hmm... I'm now wondering if we could also perhaps just hook into a keybinding for "tab" and maintain some state that we can use to prevent opening the tui on "up" until a user hits a keybinding that exits tab completion (e.g. "enter", "exit", etc...).

This way we can continue to bind to up in cases where the user is navigating history, and avoid conflicting with the behaviour of navigating tab-completion suggestions 🤔

**Comment by s0** [comment]
Here's an attempt at doing what I suggested above: #420

**Comment by ellie** [comment]
This should have been resolved in the above PR, tysm @s0! 🚀 

---

Thanks for raising this @UbiquitousPhoton + providing more detail around the issue!

Regardless of anyone's personal preferences around a feature, I'd like to make sure we try and _resolve_ future problems, rather than just disabling features by default because we don't like them

Happy to reopen this if it turns out we clobber any other default bindings, but I think it's safe to close for now!

**Comment by UbiquitousPhoton** [comment]
Blimey you lot move quickly! Many thanks for an extremely quick fix. Just to make the point, though, this issue could still exist under zsh (with something like oh-my-zsh doing completions)

**Comment by s0** [comment]
I imagine that the number of zsh users using oh-my-zsh is probably high enough (likely more than users of fish?) that if we can actually determine when a user is using it, and interacting with tab-completion in a similar way like we're doing with fish, it would be worthwhile?

**Comment by UbiquitousPhoton** [comment]
I personally migrated from zsh/oh-my-zsh to fish, so yeah I would imagine it would be worthwhile (if possible, I'm not sure how that bit works under the hood in zsh. I now rather value the documentation of fish)
